### PR TITLE
Add swiftpm support

### PR DESCRIPTION
**Pull request by sharplet**
Related to https://github.com/PersistX/PersistDB/issues/3.

### CODE REVIEW

**Comment by mdiep** [comment]
Yay! 🎉 Thanks for working on this.

Two notes:

1. Curry shouldn't be needed
2. Would you mind adding a SwiftPM build to CI too? 🙏

**Comment by sharplet** [comment]
Ah, it looks like there was a defunct test file that was no longer in the Xcode project, but still in the project tree. I've removed it and the Curry dependency it triggered.

Testing out a basic run of `swift test` on CI, haven't used Travis in a while.

**Comment by sharplet** [comment]
Apparently it worked! Hooray! 🎉

**Pull request merged**
